// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUi8_tw9lL7xCvwIZ30iqrFmFkjdsSACY',
    appId: '1:448620809328:android:217ea4fbf11f674d1e78b5',
    messagingSenderId: '448620809328',
    projectId: 'wooenglishapp',
    databaseURL: 'https://wooenglishapp-default-rtdb.firebaseio.com',
    storageBucket: 'wooenglishapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwgv872DMcu7wkcI8uC20vn2oVB-dRNiM',
    appId: '1:448620809328:ios:ee1fb09f3ed79b691e78b5',
    messagingSenderId: '448620809328',
    projectId: 'wooenglishapp',
    databaseURL: 'https://wooenglishapp-default-rtdb.firebaseio.com',
    storageBucket: 'wooenglishapp.appspot.com',
    iosClientId: '448620809328-suksd7qn0ugg4d6fbinep32jggih9qdp.apps.googleusercontent.com',
    iosBundleId: 'app.woo.english.wooEnglish',
  );
}
